package graph

// File ini secara otomatis dibuat ulang berdasarkan skema GraphQL.
// Implementasi resolver akan disalin saat regenerasi kode.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"strconv"

	"public-profile-api/graph/generated"
	"public-profile-api/graph/model"
	"public-profile-api/models"
	"public-profile-api/service"
)

// People adalah resolver untuk query 'people' yang mengembalikan daftar semua orang dalam format GraphQL.
func (r *queryResolver) People(ctx context.Context) ([]*model.Person, error) {
    // Mengambil seluruh data person dari service.
    people, err := service.GetAllPeople()
    if err != nil {
        return nil, err
    }

    // Menyiapkan slice untuk data GraphQL.
    result := make([]*model.Person, 0, len(people))

    // Mengubah setiap data internal menjadi model GraphQL.
    for _, person := range people {
        result = append(result, personToGraphQL(person))
    }

    return result, nil
}

// Person adalah resolver untuk query 'person' yang mengembalikan satu data orang berdasarkan ID.
func (r *queryResolver) Person(ctx context.Context, id string) (*model.Person, error) {
    // Mengubah ID dari String GraphQL menjadi Integer.
    personID, err := strconv.Atoi(id)
    if err != nil {
        return nil, fmt.Errorf("invalid person ID: %s", id)
    }

    // Mengambil data person berdasarkan ID melalui service.
    person, err := service.GetPersonByID(personID)
    if err != nil {
        return nil, err
    }

    // Mengubah model internal menjadi model GraphQL.
    return personToGraphQL(person), nil
}

// RandomPerson adalah resolver untuk query 'randomPerson' yang mengembalikan satu data orang acak.
func (r *queryResolver) RandomPerson(ctx context.Context) (*model.Person, error) {
    // Mengambil satu person secara acak melalui service.
    person, err := service.GetRandomPerson()
    if err != nil {
        return nil, err
    }

    // Mengubah model internal menjadi model GraphQL.
    return personToGraphQL(person), nil
}

// Query mengembalikan implementasi dari generated.QueryResolver.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }


// personToGraphQL mengubah model Person internal menjadi model Person GraphQL.
func personToGraphQL(person models.Person) *model.Person {
    // Menyiapkan daftar hobby GraphQL.
    hobbies := make([]*model.Hobby, 0, len(person.Hobbies))

    // Mengubah setiap hobby internal menjadi hobby GraphQL.
    for _, hobby := range person.Hobbies {
        hobbies = append(hobbies, &model.Hobby{
            ID:   strconv.Itoa(hobby.ID),
            Name: hobby.Name,
        })
    }

    // Mengembalikan data Person dalam format GraphQL.
    return &model.Person{
        ID:      strconv.Itoa(person.ID),
        Name:    person.Name,
        Age:     person.Age,
        Gender:  person.Gender,
        Job:     person.Job,
        Phone:   person.Phone,
        Email:   person.Email,
        Address: person.Address,
        City:    person.City,
        Country: person.Country,
        Hobbies: hobbies,
    }
}

// queryResolver adalah struct penampung resolver untuk operasi Query GraphQL.
type queryResolver struct{ *Resolver }
