package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"public-profile-api/graph/generated"
	"public-profile-api/graph/model"
)

// People is the resolver for the people field.
func (r *queryResolver) People(ctx context.Context) ([]*model.Person, error) {
	panic(fmt.Errorf("not implemented: People - people"))
}

// Person is the resolver for the person field.
func (r *queryResolver) Person(ctx context.Context, id string) (*model.Person, error) {
	panic(fmt.Errorf("not implemented: Person - person"))
}

// RandomPerson is the resolver for the randomPerson field.
func (r *queryResolver) RandomPerson(ctx context.Context) (*model.Person, error) {
	panic(fmt.Errorf("not implemented: RandomPerson - randomPerson"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
