// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Hobby struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Person struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Age     int      `json:"age"`
	Gender  string   `json:"gender"`
	Job     string   `json:"job"`
	Phone   string   `json:"phone"`
	Email   string   `json:"email"`
	Address string   `json:"address"`
	City    string   `json:"city"`
	Country string   `json:"country"`
	Hobbies []*Hobby `json:"hobbies"`
}

type Query struct {
}
